services:
  gateway:
    image: nginx:alpine
    container_name: excalidraw-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - excalidraw
      - excalidraw-room
      - excalidraw-storage-backend
    restart: always

  excalidraw:
    build:
      context: .
      args:
        - VITE_APP_WS_SERVER_URL=https://excalidraw.kid1401.com/
        - VITE_APP_BACKEND_V2_GET_URL=https://excalidraw.kid1401.com/api/v2/scenes/
        - VITE_APP_BACKEND_V2_POST_URL=https://excalidraw.kid1401.com/api/v2/scenes
    container_name: excalidraw
    restart: always

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    container_name: excalidraw-room
    environment:
      - PORT=8080
    restart: always

  excalidraw-storage-backend:
    image: kiliandeca/excalidraw-storage-backend:latest
    container_name: excalidraw-storage-backend
    environment:
      - STORAGE_TYPE=local
      - STORAGE_PATH=/app/storage
    volumes:
      - excalidraw_storage:/app/storage
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: excalidraw-tunnel
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: always

volumes:
  excalidraw_storage:
