services:
  gateway:
    image: nginx:alpine
    container_name: excalidraw-gateway-local
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - excalidraw
      - excalidraw-room
      - excalidraw-storage-backend
    restart: always

  excalidraw:
    build:
      context: .
      args:
        - VITE_APP_WS_SERVER_URL=http://localhost:8080
        - VITE_APP_BACKEND_V2_GET_URL=http://localhost:8080/api/v2/scenes/
        - VITE_APP_BACKEND_V2_POST_URL=http://localhost:8080/api/v2/scenes
    container_name: excalidraw-local
    restart: always

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    container_name: excalidraw-room-local
    environment:
      - PORT=8080
    restart: always

  excalidraw-storage-backend:
    image: kiliandeca/excalidraw-storage-backend:latest
    container_name: excalidraw-storage-backend-local
    environment:
      - STORAGE_TYPE=local
      - STORAGE_PATH=/app/storage
    volumes:
      - excalidraw_storage_local:/app/storage
    restart: always

volumes:
  excalidraw_storage_local:
